// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2WJaJFUdD-aVowcY14PPA2_hf7eKkKI',
    appId: '1:358447960876:web:75e3cd830d49d08a9e5289',
    messagingSenderId: '358447960876',
    projectId: 'linkit-9d8e1',
    authDomain: 'linkit-9d8e1.firebaseapp.com',
    storageBucket: 'linkit-9d8e1.firebasestorage.app',
    measurementId: 'G-QLQ721GWMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXS0bWHyoRokzlPjG03I3Se6mZ2hL15FA',
    appId: '1:358447960876:android:e5f15be36f63fe569e5289',
    messagingSenderId: '358447960876',
    projectId: 'linkit-9d8e1',
    storageBucket: 'linkit-9d8e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVngkP5OOCB20euR8aaV7tVuo7TYlP6A',
    appId: '1:358447960876:ios:7356ffb2437224c59e5289',
    messagingSenderId: '358447960876',
    projectId: 'linkit-9d8e1',
    storageBucket: 'linkit-9d8e1.firebasestorage.app',
    iosBundleId: 'com.example.linkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVngkP5OOCB20euR8aaV7tVuo7TYlP6A',
    appId: '1:358447960876:ios:7356ffb2437224c59e5289',
    messagingSenderId: '358447960876',
    projectId: 'linkit-9d8e1',
    storageBucket: 'linkit-9d8e1.firebasestorage.app',
    iosBundleId: 'com.example.linkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx2WJaJFUdD-aVowcY14PPA2_hf7eKkKI',
    appId: '1:358447960876:web:6e26ac547b6a58a09e5289',
    messagingSenderId: '358447960876',
    projectId: 'linkit-9d8e1',
    authDomain: 'linkit-9d8e1.firebaseapp.com',
    storageBucket: 'linkit-9d8e1.firebasestorage.app',
    measurementId: 'G-HQ95FWDEF5',
  );

}